"""
Institution story arc catalog — titled pipelines with themes, hooks, and five-beat stages.
"""

INSTITUTION_ARC_POOLS = {
    "academy": [
        {
            "title": "The Rigged Examination",
            "theme": "academic",
            "hook": "Whispers say the coming examinations were sold before the questions were written.",
            "stages": [
                "students compare notes and find identical 'lucky' answers circulating",
                "a tutor accuses a favoured pupil in public; both have alibis and enemies",
                "copied papers appear in the headmaster's desk — planted or proof",
                "the examination hall is sealed; someone still passes answers through the vents",
                "someone is expelled, promoted, or the academy loses accreditation forever",
            ],
        },
        {
            "title": "The Missing Student",
            "theme": "intrigue",
            "hook": "A student has vanished; their belongings are arranged as if they expected to return.",
            "stages": [
                "dorm mates report footsteps in an empty room after midnight",
                "a tutor knows the student's secrets and refuses to name them",
                "a forbidden book is found under the mattress — pages torn out",
                "the student sends a letter from outside the walls — or someone forges their hand",
                "the truth surfaces ugly: runaway, murder, or recruitment into something worse",
            ],
        },
        {
            "title": "The Forbidden Text",
            "theme": "academic",
            "hook": "A text the headmaster ordered burned is copied faster than the flames can eat it.",
            "stages": [
                "students meet in cellars to read by one candle shared between twelve",
                "a tutor confiscates a copy and keeps it instead of turning it in",
                "the headmaster must choose: burn readers or learn from the book",
                "city priests demand the academy surrender all copies",
                "knowledge spreads, students hang, or the text becomes curriculum",
            ],
        },
        {
            "title": "The Plagiarist Laureate",
            "theme": "academic",
            "hook": "A celebrated thesis wins patronage — and matches a dead mentor's unpublished work.",
            "stages": [
                "a junior scribe finds identical paragraphs in sealed archives",
                "the laureate offers the scribe a future or a disappearance",
                "tutors split between protecting reputation and protecting truth",
                "the dead mentor's family demands restitution in court and in print",
                "credit is restored, buried, or the academy invents a new kind of lie",
            ],
        },
        {
            "title": "Laboratory of Tongues",
            "theme": "intrigue",
            "hook": "Language tutors teach dialects that match coded letters intercepted at the docks.",
            "stages": [
                "students fluent in the new dialect receive private stipends",
                "a tutor disappears after asking who funds the 'philology prize'",
                "foreign agents attend public lectures disguised as merchants",
                "the headmaster sells translations to the garrison and the guild",
                "the academy becomes a cipher house, is raided, or burns its notebooks",
            ],
        },
        {
            "title": "The Duelist's Curriculum",
            "theme": "nobility",
            "hook": "Honour classes spill into real blades; parents pay for wins, not wisdom.",
            "stages": [
                "a student dies in 'practice'; the report lists accidental fall",
                "tutors who refuse to teach killing are reassigned to scullery",
                "noble parents intervene when their heirs lose",
                "a common-born prodigy beats heirs too publicly to ignore",
                "duelling is banned, institutionalised, or moves to the garden maze",
            ],
        },
        {
            "title": "Clockwork Examination",
            "theme": "academic",
            "hook": "Mechanical tutors grade papers without sleep — and favour whoever oils them.",
            "stages": [
                "students bribe engineers instead of tutors",
                "a machine marks everyone wrong on the same question",
                "sabotage is discovered — or blamed on the wrong faculty",
                "the city guild demands the academy share patent profits",
                "machines are smashed, licensed, or replace the headmaster",
            ],
        },
    ],
    "guild": [
        {
            "title": "The Undercut Contract",
            "theme": "corruption",
            "hook": "A lucrative city contract is up for bidding; numbers leak before the sealed envelopes open.",
            "stages": [
                "a rival guild undercuts by exactly one day's labour — too precise to guess",
                "an apprentice is caught listening at the master's door",
                "violence at the bidding hall is called a drunken quarrel",
                "both guilds discover the same patron paid them to fight",
                "the contract is won in blood, shared in compromise, or awarded to a third liar",
            ],
        },
        {
            "title": "Empty Coffers",
            "theme": "corruption",
            "hook": "Coin has gone missing from the guild vault; the lock shows no tampering.",
            "stages": [
                "suspicion falls on a journeyman with gambling debts",
                "the master demands a reckoning that feels like a purge",
                "a second theft happens during the investigation — someone is watching",
                "ledgers reveal payments to a name that doesn't exist",
                "a thief is named rightly or not; the guild splits or reunites poorer",
            ],
        },
        {
            "title": "Street Feud",
            "theme": "crime",
            "hook": "A feud with a rival guild simmers over a shared well that poisoned two apprentices.",
            "stages": [
                "brawls spill into the market; the watch collects fines and looks away",
                "both masters accuse the other of hiring dock thugs",
                "a truce meeting is bombed with nothing but stink smoke — message clear",
                "city council threatens to revoke both charters",
                "the feud ends in pact, absorption, or a body no one claims",
            ],
        },
        {
            "title": "The Ghost Journeyman",
            "theme": "intrigue",
            "hook": "Work signed by a master bears a journeyman's mark — but that journeyman died last winter.",
            "stages": [
                "quality rises; so do accidents on sites only the dead man knew",
                "apprentices swear they saw him in the forge after closing",
                "the master sells pieces no living hand could finish in time given",
                "rivals accuse necromancy, fraud, or a hidden twin",
                "the truth sells for patent, persecution, or patronage",
            ],
        },
        {
            "title": "Apprentice Auction",
            "theme": "corruption",
            "hook": "Families bid secretly for apprenticeship slots the guild claims are merit-based.",
            "stages": [
                "talented poor children lose places to dull sons of merchants",
                "a clerk sells the roster; the master pretends shock",
                "a rejected apprentice sabotages a public commission",
                "the city demands open trials; the guild demands tradition",
                "slots are reformed, sold openly, or the guild moves underground",
            ],
        },
        {
            "title": "The Patent Knife",
            "theme": "intrigue",
            "hook": "A new blade design cuts armour the garrison swore was proof — patents and bribes cross.",
            "stages": [
                "smuggled designs appear in rival forges before the patent is filed",
                "a journeyman vanishes with the only prototype",
                "the garrison orders exclusivity at sword-point",
                "assassins test the blade on living targets",
                "the design spreads, is suppressed, or wins a war",
            ],
        },
        {
            "title": "Masterless Charter",
            "theme": "crime",
            "hook": "The guild master dies without naming successor; three journeymen claim the seal.",
            "stages": [
                "charter law is argued by scribes paid by each claimant",
                "apprentices are pressed to swear oaths before they understand them",
                "a locked strongroom opens for one claimant — and not the others",
                "violence is postponed by a shared enemy, then resumes louder",
                "one master reigns, three guilds split, or the charter is revoked",
            ],
        },
    ],
    "temple": [
        {
            "title": "The Spreading Heresy",
            "theme": "heresy",
            "hook": "Acolytes copy sermons that contradict the high priest — and draw larger crowds.",
            "stages": [
                "a cleric is implicated by a penitent who may be lying for coin",
                "miracles happen in alleys, not on the altar",
                "the high priest convenes judgement behind barred doors",
                "faithful split over one word in a creed older than the building",
                "the temple purges, splits, or adopts the heresy as reform",
            ],
        },
        {
            "title": "The Undelivered Relic",
            "theme": "heresy",
            "hook": "A relic promised to the altar never arrives; the courier's escort did, minus heads.",
            "stages": [
                "an acolyte claims to have seen a sign in the empty reliquary",
                "merchants offer to 'find' the relic for a tithe",
                "the high priest sends armed pilgrims to retrieve it",
                "a false relic arrives first and works miracles anyway",
                "faith is rewarded, mocked, or weaponised against rivals",
            ],
        },
        {
            "title": "Tithes in Blood",
            "theme": "corruption",
            "hook": "Collection records show full tithes while parishioners swear they gave nothing.",
            "stages": [
                "collectors carry weapons beneath their robes",
                "a farmer beaten for short payment was marked paid in ink",
                "the high priest's nephew buys land with inexplicable coin",
                "parishioners stop coming; the temple blames heretics",
                "accounts open, collectors hang, or the temple hires mercenaries",
            ],
        },
        {
            "title": "The Silent Choir",
            "theme": "intrigue",
            "hook": "The choir stops singing mid-hymn on the same verse each week; the congregation listens harder.",
            "stages": [
                "rumours say the omitted verse names a living sin of the high priest",
                "a chorister is found mute — tongue unharmed, will broken",
                "nobles attend just to hear what stops the music",
                "the verse is sung once in full; someone dies that night",
                "the hymn is rewritten, censored, or becomes a battle cry",
            ],
        },
        {
            "title": "Sanctuary for Sale",
            "theme": "corruption",
            "hook": "Criminals buy sanctuary time by the hour; the poor are turned away at the door.",
            "stages": [
                "a murderer walks free while a debtor is dragged out by the watch",
                "a cleric refuses payment; reassigned to a village with no walls",
                "evidence ties sanctuary fees to dock smuggling tithes",
                "the city revokes sanctuary rights unless the temple pays tax",
                "sanctuary ends, goes underground, or prices only the rich forever",
            ],
        },
        {
            "title": "The Prophet of Rain",
            "theme": "heresy",
            "hook": "A street prophet predicts drought; wells fail on schedule enough to frighten clerics.",
            "stages": [
                "crowds follow the prophet instead of the procession",
                "the temple calls it trickery; the trickery works anyway",
                "a cleric duplicates the prophecy and is struck by lightning or scandal",
                "nobles fund the prophet to hurt rival harvests",
                "rain returns, the prophet is martyred, or the temple hires them",
            ],
        },
        {
            "title": "Reliquary War",
            "theme": "intrigue",
            "hook": "Two temples claim the same bone; both miracles happen on the same day.",
            "stages": [
                "pilgrims fight in the street over which queue heals faster",
                "scholars carbon-date faith; results are inconvenient",
                "one reliquary is stolen; miracles continue at the empty stand",
                "assassins target translators of the bone's provenance scroll",
                "one bone wins, both share pilgrims, or neither is holy",
            ],
        },
    ],
    "garrison": [
        {
            "title": "Deserting Dawn",
            "theme": "crime",
            "hook": "Recruits vanish between midnight roll call and morning bread.",
            "stages": [
                "a soldier is suspected of forging passes — or helping others escape",
                "the captain tightens the leash; punishments grow theatrical",
                "deserters send letters home from cities the army isn't fighting",
                "someone in the officer's mess is selling routes",
                "an example is made — of a deserter, a helper, or the captain",
            ],
        },
        {
            "title": "Movement on the Wall",
            "theme": "intrigue",
            "hook": "Scouts report fires beyond the wall; the garrison is undermanned and overconfident.",
            "stages": [
                "a recruit raises a false alarm to impress a captain",
                "real movement is ignored as cry-wolf until too late",
                "supplies marked for the wall are found in a merchant's cellar",
                "officers argue whether the threat is army, plague, or politics",
                "something arrives — army, refugees, or nothing but panic",
            ],
        },
        {
            "title": "The Captain's Bribe",
            "theme": "corruption",
            "hook": "Smugglers pass the gate on schedule; the captain's new house has no honest salary.",
            "stages": [
                "a soldier of conscience gathers proof and asks the wrong priest to bless it",
                "loyalties fracture along pay lines, not honour lines",
                "the captain offers promotion to bury the ledger",
                "a smuggler turns witness to hurt a rival route",
                "the truth costs someone everything — often more than one person",
            ],
        },
        {
            "title": "The False Mustermaster",
            "theme": "corruption",
            "hook": "Pay rolls list soldiers who don't exist; real recruits eat half rations.",
            "stages": [
                "a clerk dies falling down stairs that weren't wet",
                "recruits compare names on the roll to faces in the yard",
                "officers threaten mutiny and call it loyalty",
                "the city council audits; the garrison locks the gate",
                "ghost soldiers are erased, or the fraud spreads to the council",
            ],
        },
        {
            "title": "Siege in Peace",
            "theme": "nobility",
            "hook": "The garrison drills for siege while merchants protest lost trade.",
            "stages": [
                "nobles fund extra drills to intimidate rivals in the high quarter",
                "a 'practice' bolt kills a market hawker; called accident",
                "soldiers are billeted in homes without consent",
                "a merchant hires thieves to steal drill plans",
                "siege posture ends in coup, apology, or real siege",
            ],
        },
        {
            "title": "The Broken Standard",
            "theme": "intrigue",
            "hook": "The regiment's battle standard is swapped overnight; the old one burns in the yard.",
            "stages": [
                "veterans refuse to march under colours they don't recognise",
                "the new standard bears a noble house crest not on any charter",
                "a spy is suspected; the suspect is the captain's favourite",
                "mutiny is whispered in languages the officers don't speak",
                "colours revert, mutiny breaks, or the regiment changes allegiance",
            ],
        },
        {
            "title": "Mercenary Charter",
            "theme": "crime",
            "hook": "The garrison takes private coin to guard merchants, not the city walls.",
            "stages": [
                "a poor district fire burns while soldiers escort a silk caravan",
                "the captain calls it 'partnership'; the council calls it theft",
                "merchants compete to hire the same platoon on the same night",
                "a soldier dies defending cargo, not people — funeral is private",
                "charter is revoked, expanded, or the garrison becomes a company",
            ],
        },
    ],
    "hunters_lodge": [
        {
            "title": "The Unpaid Bounty",
            "theme": "hunt",
            "hook": "A dire beast is killed; the carcass is gone before the warden can measure teeth.",
            "stages": [
                "trackers argue over who made the kill with no proof but blood on boots",
                "the warden posts a harsher contract with penalties for false claims",
                "poachers sell parts in the market under guild noses",
                "a noble claims the kill by virtue of owning the forest",
                "poachers, heroes, or liars are named — and paid or hanged",
            ],
        },
        {
            "title": "Hollow Woods",
            "theme": "hunt",
            "hook": "Something in the deep woods takes hunters; traps are found sprung and empty.",
            "stages": [
                "the lodge sends a pair to scout; one returns speaking in wrong tenses",
                "trees bear claw marks too high for any beast local lore knows",
                "villagers refuse to guide at any price",
                "the warden orders a cull; veterans refuse the order",
                "one returns changed, both vanish, or the woods get a new name",
            ],
        },
        {
            "title": "The Noble Trophy",
            "theme": "nobility",
            "hook": "A lord wants a trophy beast for his hall; coin flows but the warden refuses the hunt.",
            "stages": [
                "pressure from the city watch mounts on behalf of the noble",
                "hunters are offered private coin to break lodge rules",
                "the beast is herded toward the noble's estate instead of killed clean",
                "a village is endangered to drive the creature where spectators wait",
                "the hunt happens anyway — with consequences counted in bodies",
            ],
        },
        {
            "title": "Snare for Man",
            "theme": "crime",
            "hook": "Traps meant for boars catch humans; the lodge denies knowledge, not guilt.",
            "stages": [
                "a poacher is found dead in a licensed snare line",
                "trackers recognise knot-work belonging to a lodge legend",
                "the warden accuses rivals of framing the lodge",
                "survivors describe being herded like game",
                "traps are pulled, re-set for men, or the warden disappears",
            ],
        },
        {
            "title": "The White Stag",
            "theme": "hunt",
            "hook": "Sightings of a white stag precede deaths — hunters argue omen versus bait.",
            "stages": [
                "nobles forbid common hunters from pursuing it",
                "multiple parties enter the wood; one doesn't return on schedule",
                "the stag is seen in two places at once",
                "a tracker swears it led her to a grave not on any map",
                "the stag dies, vanishes, or becomes property of the crown",
            ],
        },
        {
            "title": "Fang Market",
            "theme": "corruption",
            "hook": "Beast parts sell in the market with lodge seals forged well enough to fool apprentices.",
            "stages": [
                "real hunters can't sell meat; fakes undercut them",
                "a forged seal implicates the warden's clerk",
                "alchemists pay premium for parts from beasts never listed as killed",
                "the lodge raids the market; the watch raids the lodge",
                "forgery ring breaks, or the lodge starts selling fakes itself",
            ],
        },
        {
            "title": "The Warden's Trial",
            "theme": "intrigue",
            "hook": "The warden faces a lodge vote after three failed hunts — accidents or sabotage?",
            "stages": [
                "hunters split into camps backing rival warden candidates",
                "sabotaged traps kill a popular tracker",
                "foreign hunters arrive with royal letters bypassing lodge law",
                "the vote becomes a fight with rules remembered differently by each side",
                "leadership changes, lodge splits, or old warden keeps power by blood",
            ],
        },
    ],
}

INSTITUTION_HOOKS = {
    "academy": "Students and tutors circle a crisis that could end careers — or lives.",
    "guild": "Masters, apprentices, and rivals fight over contracts, coin, and secrets.",
    "temple": "Faith, politics, and guilt intertwine behind sanctified doors.",
    "garrison": "Soldiers, recruits, and officers brace for trouble inside and out.",
    "hunters_lodge": "Trackers, hunters, and the warden trade bounties, pelts, and warnings of what stirs in the wild.",
}
